"""Base Uniswap V3 in-memory source boundary (Phase 8C.4)."""

from newcoin_trader.sources.base_uniswap_v3.acquisition import (
    AcquisitionError,
    AcquisitionFailure,
    AcquisitionFailureResult,
    BaseEvidenceAcquirer,
)
from newcoin_trader.sources.base_uniswap_v3.adapter import (
    AdapterRequest,
    adapt_dex_first_trade,
    build_eligible_scope,
    compute_realized_execution_price,
    normalize_historical_swap_point_observation,
    select_earliest_valid_swap,
    validate_factory_universe,
)
from newcoin_trader.sources.base_uniswap_v3.contracts import (
    CHAIN_ID,
    FACTORY_ADDRESS,
    POOL_CREATED_TOPIC,
    PROTOCOL_VERSION,
    SWAP_TOPIC,
)
from newcoin_trader.sources.base_uniswap_v3.models import (
    CanonicalPoolCreatedEvidence,
    CanonicalSwapEvidence,
    CapAmbiguityError,
    CapPolicy,
    ExactPoolHistoryScanProof,
    FactoryDeploymentAnchor,
    FactoryPoolCreatedRecord,
    FactoryUniverseScanProof,
    FinalityBoundary,
    HistoricalSwapPointObservation,
    ScanKind,
    ScanLedgerEntry,
    ScanStatus,
    SwapLogRecord,
    TokenDecimalsEvidence,
    VerifiedBlock,
    VerifiedExactPoolSwapScanResult,
    VerifiedFactoryUniverse,
    VerifiedReceipt,
    compute_canonical_swap_candidates_digest,
)
from newcoin_trader.sources.base_uniswap_v3.pool_created_decoder import decode_pool_created_log
from newcoin_trader.sources.base_uniswap_v3.provider import (
    BaseRpcProvider,
    RpcCallResult,
    RpcCapabilityProfile,
    RpcError,
    RpcMethodError,
    RpcResponseError,
    RpcTransportError,
    sanitize_rpc_endpoint,
)
from newcoin_trader.sources.base_uniswap_v3.scan_ledger import InMemoryScanLedger
from newcoin_trader.sources.base_uniswap_v3.swap_decoder import decode_swap_log

__all__ = [
    "CHAIN_ID",
    "FACTORY_ADDRESS",
    "POOL_CREATED_TOPIC",
    "PROTOCOL_VERSION",
    "SWAP_TOPIC",
    "AdapterRequest",
    "AcquisitionError",
    "AcquisitionFailure",
    "AcquisitionFailureResult",
    "BaseEvidenceAcquirer",
    "BaseRpcProvider",
    "CanonicalPoolCreatedEvidence",
    "CanonicalSwapEvidence",
    "CapAmbiguityError",
    "CapPolicy",
    "FactoryDeploymentAnchor",
    "ExactPoolHistoryScanProof",
    "FactoryPoolCreatedRecord",
    "FactoryUniverseScanProof",
    "FinalityBoundary",
    "HistoricalSwapPointObservation",
    "InMemoryScanLedger",
    "ScanKind",
    "ScanLedgerEntry",
    "ScanStatus",
    "RpcCallResult",
    "RpcCapabilityProfile",
    "RpcError",
    "RpcMethodError",
    "RpcResponseError",
    "RpcTransportError",
    "SwapLogRecord",
    "TokenDecimalsEvidence",
    "VerifiedBlock",
    "VerifiedFactoryUniverse",
    "VerifiedExactPoolSwapScanResult",
    "VerifiedReceipt",
    "adapt_dex_first_trade",
    "build_eligible_scope",
    "compute_canonical_swap_candidates_digest",
    "compute_realized_execution_price",
    "normalize_historical_swap_point_observation",
    "decode_pool_created_log",
    "decode_swap_log",
    "select_earliest_valid_swap",
    "sanitize_rpc_endpoint",
    "validate_factory_universe",
]
